runtime: python
env: flex

runtime_config:
  python_version: 3

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.5

env_variables:
  MYSQL_HOST: 34.128.84.86
  MYSQL_USER: root
  MYSQL_PASSWORD: freshcan123
  MYSQL_DB: fresh_scan_db

entrypoint: gunicorn -b :$PORT app:app